spring.application.name=itmanagement

# Render Dynamic Port Configuration
server.port=${PORT:8080}

# Railway MySQL Remote Database Connection
spring.datasource.url=jdbc:mysql://sakura.proxy.rlwy.net:30798/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=iqszGjgqTQcLXZLixqtDxPbmdlaBYCpD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true