spring.application.name=itmanagement

# Render Port Binding
server.port=${PORT:8080}

# Database Connection (Reads directly from Render Environment Variables)
spring.datasource.url=${mysql://root:iqszGjgqTQclXZLixqtDxPbmdlaBYCpD@mysql.railway.internal:3306/railway}
spring.datasource.username=${root}
spring.datasource.password=${iqszGjgqTQclXZLixqtDxPbmdlaBYCpD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true